apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: ghcr.io/victorabaah/edge-app:v1
    # CI/CD updates this tag for approved production promotion
    newTag: latest
