apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: ghcr.io/victorabaah/edge-app:v1
    # CI/CD updates this tag in GitOps promotion
    newTag: latest
